/**
 * Repository for suppliers data access.
 * 
 * This repository implements the Repository Pattern for the Supplier entity,
 * providing a clean abstraction layer between the API routes and the SQLite database.
 * All SQL queries are parameterized to prevent SQL injection attacks.
 * 
 * @module SuppliersRepository
 */

import { getDatabase, DatabaseConnection } from '../db/sqlite';
import { Supplier } from '../models/supplier';
import { handleDatabaseError, NotFoundError } from '../utils/errors';
import { buildInsertSQL, buildUpdateSQL, objectToCamelCase } from '../utils/sql';

/**
 * Repository class for managing supplier data operations.
 * Handles all CRUD operations for suppliers in the database.
 */
export class SuppliersRepository {
  private db: DatabaseConnection;

  /**
   * Creates a new SuppliersRepository instance.
   * @param {DatabaseConnection} db - SQLite database connection
   */
  constructor(db: DatabaseConnection) {
    this.db = db;
  }

  /**
   * Retrieves all suppliers from the database.
   * Results are ordered by supplier ID in ascending order.
   * 
   * @returns {Promise<Supplier[]>} Array of all supplier objects
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * const repo = await getSuppliersRepository();
   * const suppliers = await repo.findAll();
   * // Returns: [{ supplierId: 1, name: 'Tech Supplies Inc', ... }, ...]
   */
  async findAll(): Promise<Supplier[]> {
    try {
      const rows = await this.db.all<any>('SELECT * FROM suppliers ORDER BY supplier_id');
      return rows.map((row) => objectToCamelCase(row) as Supplier);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves a single supplier by their unique ID.
   * 
   * @param {number} id - Supplier ID
   * @returns {Promise<Supplier | null>} Supplier object if found, null otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * const supplier = await repo.findById(1);
   * if (supplier) {
   *   console.log(supplier.name);
   * }
   */
  async findById(id: number): Promise<Supplier | null> {
    try {
      const row = await this.db.get<any>('SELECT * FROM suppliers WHERE supplier_id = ?', [id]);
      return row ? (objectToCamelCase(row) as Supplier) : null;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Creates a new supplier in the database.
   * The supplier ID is auto-generated by the database.
   * 
   * @param {Omit<Supplier, 'supplierId'>} supplier - Supplier data without ID
   * @returns {Promise<Supplier>} The created supplier with generated ID
   * @throws {ValidationError} If required fields are missing
   * @throws {ConflictError} If constraint violations occur
   * @throws {DatabaseError} If the database operation fails
   * 
   * @example
   * const newSupplier = await repo.create({
   *   name: 'New Supplier Corp',
   *   email: 'contact@newsupplier.com',
   *   phone: '555-1234'
   * });
   */
  async create(supplier: Omit<Supplier, 'supplierId'>): Promise<Supplier> {
    try {
      const { sql, values } = buildInsertSQL('suppliers', supplier);
      const result = await this.db.run(sql, values);

      const createdSupplier = await this.findById(result.lastID!);
      if (!createdSupplier) {
        throw new Error('Failed to retrieve created supplier');
      }

      return createdSupplier;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates an existing supplier's information.
   * Supports partial updates - only provided fields will be updated.
   * 
   * @param {number} id - Supplier ID to update
   * @param {Partial<Omit<Supplier, 'supplierId'>>} supplier - Partial supplier data to update
   * @returns {Promise<Supplier>} The updated supplier object
   * @throws {NotFoundError} If the supplier with the given ID does not exist
   * @throws {ValidationError} If update data is invalid
   * @throws {DatabaseError} If the database operation fails
   * 
   * @example
   * const updated = await repo.update(1, { name: 'Updated Name' });
   */
  async update(id: number, supplier: Partial<Omit<Supplier, 'supplierId'>>): Promise<Supplier> {
    try {
      const { sql, values } = buildUpdateSQL('suppliers', supplier, 'supplier_id = ?');
      const result = await this.db.run(sql, [...values, id]);

      if (result.changes === 0) {
        throw new NotFoundError('Supplier', id);
      }

      const updatedSupplier = await this.findById(id);
      if (!updatedSupplier) {
        throw new Error('Failed to retrieve updated supplier');
      }

      return updatedSupplier;
    } catch (error) {
      handleDatabaseError(error, 'Supplier', id);
    }
  }

  /**
   * Deletes a supplier from the database.
   * Note: This will cascade delete all related products and deliveries
   * due to foreign key constraints (ON DELETE CASCADE).
   * 
   * @param {number} id - Supplier ID to delete
   * @returns {Promise<void>}
   * @throws {NotFoundError} If the supplier with the given ID does not exist
   * @throws {ConflictError} If the supplier cannot be deleted due to constraints
   * @throws {DatabaseError} If the database operation fails
   * 
   * @example
   * await repo.delete(1);
   */
  async delete(id: number): Promise<void> {
    try {
      const result = await this.db.run('DELETE FROM suppliers WHERE supplier_id = ?', [id]);

      if (result.changes === 0) {
        throw new NotFoundError('Supplier', id);
      }
    } catch (error) {
      handleDatabaseError(error, 'Supplier', id);
    }
  }

  /**
   * Checks if a supplier exists in the database.
   * 
   * @param {number} id - Supplier ID to check
   * @returns {Promise<boolean>} True if supplier exists, false otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * const exists = await repo.exists(1);
   * if (!exists) {
   *   throw new Error('Supplier not found');
   * }
   */
  async exists(id: number): Promise<boolean> {
    try {
      const result = await this.db.get<{ count: number }>(
        'SELECT COUNT(*) as count FROM suppliers WHERE supplier_id = ?',
        [id],
      );
      return (result?.count || 0) > 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Searches for suppliers by name using partial matching.
   * Uses case-insensitive LIKE query for flexible searching.
   * 
   * @param {string} name - Name or partial name to search for
   * @returns {Promise<Supplier[]>} Array of matching suppliers, ordered by name
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * const results = await repo.findByName('Tech');
   * // Returns all suppliers with 'Tech' in their name
   */
  async findByName(name: string): Promise<Supplier[]> {
    try {
      const rows = await this.db.all<any>(
        'SELECT * FROM suppliers WHERE name LIKE ? ORDER BY name',
        [`%${name}%`],
      );
      return rows.map((row) => objectToCamelCase(row) as Supplier);
    } catch (error) {
      handleDatabaseError(error);
    }
  }
}

/**
 * Factory function to create a new repository instance.
 * Creates a fresh database connection for the repository.
 * 
 * @param {boolean} isTest - Whether to use in-memory test database
 * @returns {Promise<SuppliersRepository>} New repository instance
 */
export async function createSuppliersRepository(
  isTest: boolean = false,
): Promise<SuppliersRepository> {
  const db = await getDatabase(isTest);
  return new SuppliersRepository(db);
}

// Singleton instance for default usage
let suppliersRepo: SuppliersRepository | null = null;

/**
 * Gets or creates the singleton suppliers repository instance.
 * In test environments, always creates a new instance with in-memory database.
 * 
 * @param {boolean} isTest - Whether to use in-memory test database
 * @returns {Promise<SuppliersRepository>} Singleton or new repository instance
 * 
 * @example
 * // In application code
 * const repo = await getSuppliersRepository();
 * 
 * // In test code
 * const testRepo = await getSuppliersRepository(true);
 */
export async function getSuppliersRepository(
  isTest: boolean = false,
): Promise<SuppliersRepository> {
  const isTestEnv = isTest || process.env.NODE_ENV === 'test' || process.env.VITEST === 'true';
  if (isTestEnv) {
    return createSuppliersRepository(true);
  }
  if (!suppliersRepo) {
    suppliersRepo = await createSuppliersRepository(false);
  }
  return suppliersRepo;
}
